---
title: "Replication Analysis"
author: "Daniel Wurgaft"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    number_sections: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    theme: paper
---
# Initialization
```{r, message=FALSE}
rm(list=ls())
library(here)
library(lme4)
library(tidyverse)
theme_set(theme_bw())
```

```{r, eval=FALSE}
library(tidylog)
```


# Preprocessing

## Functions
```{r}
```

## Read data
```{r, message=FALSE}
df_raw <- read_csv(here("data/learning-instructions.csv"))
```

## Process data
```{r, message=FALSE}
df_catch = df_raw %>% filter(type == "catch trial") %>% 
                      filter(pass == FALSE) 


df_proc <- df_raw %>% 
            # exclude participants who failed a catch trial
            filter(!(run_id %in% unique(df_catch$run_id))) 

df_ME = df_proc %>% filter(type=="ME trial") %>% mutate(follows_ME = case_when(
  .$example_color == .$response ~ 0,
  .$example_color != .$response ~ 1,
  .default = NA)) %>% select(c(run_id, pool_size, num_counters, follows_ME))

df_concat = df_proc %>% filter(type=="concat trial") %>% mutate(
  concat_type = case_when(
        .$target == paste0(.$example2_name, " ", .$example1_name," ", .$example1_name) ~ "multiple repetitions concat",
    .$examples == paste0(.$example1_name, " ", .$example1_color, ", ",.$example2_name, " ", .$example2_color) ~ "simple concat",
    .default = "Multiple colors concat")) %>% mutate(follows_iconicConcat = case_when(
  (.$concat_type == "simple concat" & .$response == paste0(.$example1_color,  .$example2_color)) ~ 1,
    (.$concat_type == "multiple repetitions concat" & .$response == paste0(.$example2_color, .$example1_color,  .$example1_color)) ~ 1,
  (.$concat_type == "Multiple colors concat" & .$response == paste0(.$example1_color, .$example1_color, .$example1_color,  .$example2_color,  .$example2_color)) ~ 1,
  .default = 0
))


df_ME_vs_OneToOne = df_proc %>% filter(type=="ME_vs_OneToOne trial")  %>% mutate(follows_ME = case_when(
  nchar(.$response) > 1 ~ 1,
  .default = 0 
))

```


```{r, echo=FALSE}
# ------ End Preprocessing ------ #
# ----- Run all chunks above -----#
```
# ME analysis

## ME plot
```{r}
df_ME_summarized = df_ME %>% group_by(pool_size, num_counters) %>% summarize(percent_follows_ME = mean(follows_ME)*100)

group.colors <- c("2" = "#666BFF", "6" = "#F8766D")

ggplot(data = df_ME_summarized, aes(x = num_counters, y = percent_follows_ME, fill = as.factor(pool_size))) +
  geom_bar(stat = "identity", position = position_dodge(), alpha = 0.75) + xlab("Number of counter examples") + ylab("Percent follow ME") + labs(fill="Pool size") +  scale_fill_manual(values=group.colors)
```

# ME result 
```{r}
model_fit <- glmer(follows_ME ~ pool_size + num_counters + (1 | run_id), data = df_ME,  family = binomial)
summary(model_fit)
```

# concat result

```{r}
df_concat_summarize = df_concat %>%  group_by(run_id) %>% summarize(percent_follows_iconicConcat = mean(follows_iconicConcat)*100)


ggplot(data = df_concat_summarize, aes(x = as.factor(run_id), y = percent_follows_iconicConcat)) +
  geom_bar(stat = "identity",fill="#666BFF", position = position_dodge(), alpha = 0.75) + xlab("Participant ID") + ylab("Percent follow iconic concatenation") 
```

# ME vs one to one result

```{r}
df_ME_vs_OneToOne_summarize = df_ME_vs_OneToOne %>% group_by(run_id) %>%  summarize(percent_follows_ME = mean(follows_ME)*100)


ggplot(data = df_ME_vs_OneToOne_summarize, aes(x = as.factor(run_id), y = percent_follows_ME)) +
  geom_bar(stat = "identity", fill="#666BFF",position = position_dodge(), alpha = 0.75) + xlab("Participant ID") + ylab("Percent follow ME") 
```

# Session Info
```{r}
sessionInfo()
```

