---
title: "Replication of Experiment 2 in Human few-shot learning of compositional instructions by Brenden M. Lake, Tal Linzen, & Marco Baroni (2019, Proceedings of the 41st Annual Conference of the Cognitive Science Society)"
author: "Daniel Wurgaft (wurgaft@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

### Justification for Choice of Experiment
Lake et al. (2019) investigated how humans learn novel concepts and make compositional generalizations. To do so, they used a task in which participants must learn mappings between instructions written in a simple pseudolanguage and sequences of symbols. I chose to replicate experiment 2 from the study, as that experiment provided insight into three inductive biases that guide human generalizations. This experiment is highly relevant for my work as I study the computational basis of concept learning and generalization in humans and ML models, and one of my central interests is understanding what inductive biases allow humans to learn from sparse data and generalize systematically. 

### Stimuli and Procedures
#### Main procedures
The experiment tested the influence of three inductive biases on human generalizations: 1) Mutual exclusivity: the tendancy to associate a novel name with a novel object rather than an object that is already familiar by a different name. 2) One-to-one mappings: the tendancy to map a single input symbol to a single output symbol. 3) Iconic concatenation: the tendancy to concatanate output symbols in the order they were provided in the input. To study these biases, participants were provided with mappings between instructions and colored circles, and were then provided a test instruction and asked to provide its corresponding output sequence of colored circles. 

#### Stimuli and Procedures
There were 14 trials in total. To test each of the biases, three variables were manipulated: whether the test instruction was a novel psuedoword or a composition of the previous instructions, the number of colored circles that can be used to construct the output sequence, and the number of provided mappings between different pseudowords and a single circle (these acted as counter examples to mutual exclusivity). Stimuli in the experiment consisted of 20 pseudowords and 8 colored circles. Each of the 14 trials in experiment 2 were independent, hence, the mappings between colored circles and psuedowords were re-assigned randomly in each trial. Some of the possible challenges for this project include: Programming the experiment interface and randomizing the instruction-circle mappings in each trial and replicating the trial sequence as accurately as possible (details may require contacting authors).

### Links to Repository and Original Paper:
Link to the repository: https://github.com/psych251/lake2019/tree/main
Link to original paper: https://github.com/psych251/lake2019/blob/main/original_paper/1901.04587.pdf

## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
